/* Ports of crates/base/src/{history,undo_history}.rs tests. */
#include "Test.h"

static void ExpectHistory(const Vec<int>& values, int a, int b = -1,
                          int c = -1) {
    int n = c >= 0 ? 3 : b >= 0 ? 2 : 1;
    utassert(values.len == n);
    if (values.len != n) return;
    utassert(values[0] == a);
    if (n > 1) utassert(values[1] == b);
    if (n > 2) utassert(values[2] == c);
}
static bool HistoryEven(const int& n, void*) {
    return n % 2 == 0;
}
static void NavigationHistory() {
    TestSuite("navigation history");
    History<int> h;
    int n = 0;
    h.MaxEntries(3);
    h.Push(1);
    h.Push(2);
    h.Push(3);
    utassert(*h.Current() == 3);
    utassert(h.Back(&n) && n == 2);
    utassert(h.Back(&n) && n == 1);
    utassert(!h.Back());
    utassert(h.Forward(&n) && n == 2);
    ExpectHistory(h.Entries(), 1, 2);
    utassert(h.ForwardEntries().len == 1 && h.ForwardEntries()[0] == 3);
    utassert(h.CanBack() && h.CanForward());
    h.Push(4);
    ExpectHistory(h.Entries(), 1, 2, 4);
    utassert(!h.CanForward() && !h.Forward());
    h.Clear();
    h.Push(1);
    h.Push(2);
    h.Push(1);
    utassert(h.Back(&n) && n == 2);
    utassert(h.Back(&n) && n == 1);
    h.Clear();
    h.MaxEntries(2);
    h.Push(1);
    h.Push(2);
    h.Push(3);
    ExpectHistory(h.Entries(), 2, 3);
    utassert(h.Back(&n) && n == 2);
    utassert(!h.Back());
    h.MaxEntries(1);
    utassert(h.Forward(&n) && n == 3);
    ExpectHistory(h.Entries(), 3);
    utassert(!h.Back());
    h.MaxEntries(0);
    h.Push(1);
    utassert(!h.Current() && !h.CanBack() && !h.CanForward());
    h.MaxEntries(3);
    h.ReplaceCurrent(1);
    h.Push(2);
    h.ReplaceCurrent(3);
    ExpectHistory(h.Entries(), 1, 3);
    h.Push(4);
    h.Back();
    utassert(h.RemoveCurrent(&n) && n == 3);
    utassert(*h.Current() == 1 && h.ForwardEntries()[0] == 4);
    utassert(h.Forward(&n) && n == 4);
    h.Clear();
    h.MaxEntries(1000);
    for (int i = 1; i <= 8; i++) h.Push(i);
    for (int i = 0; i < 4; i++) h.Back();
    h.Retain(HistoryEven);
    ExpectHistory(h.Entries(), 2, 4);
    utassert(h.ForwardEntries().len == 2);
    utassert(h.ForwardEntries()[0] == 6 && h.ForwardEntries()[1] == 8);
    utassert(h.Forward(&n) && n == 6);
    utassert(h.Forward(&n) && n == 8);
    h.Back();
    h.Clear();
    utassert(!h.Current() && !h.CanBack() && !h.CanForward());
    utassert(h.Entries().len == 0 && h.ForwardEntries().len == 0);
}
static void TransactionHistory() {
    TestSuite("undo history");
    UndoHistory<int> h;
    h.StartGrouping();
    h.Push(1);
    h.Push(2);
    h.Push(3);
    h.EndGrouping();
    ExpectHistory(h.Undo(), 3, 2, 1);
    ExpectHistory(h.Redo(), 1, 2, 3);
    h.Clear();
    h.Push(1);
    h.Push(2);
    ExpectHistory(h.Undo(), 2);
    ExpectHistory(h.Undo(), 1);
    h.GroupInterval(60);
    h.Push(1);
    h.Push(2);
    ExpectHistory(h.Undo(), 2, 1);
    h.Clear();
    h.hasGroupInterval = false;
    h.Push(1);
    h.Push(2);
    h.GroupInterval(60);
    ExpectHistory(h.Undo(), 2);
    h.Push(3);
    ExpectHistory(h.Undo(), 3);
    ExpectHistory(h.Undo(), 1);
    h.Clear();
    h.hasGroupInterval = false;
    h.Push(1);
    h.Push(2);
    ExpectHistory(h.Undo(), 2);
    ExpectHistory(h.Redo(), 2);
    h.GroupInterval(60);
    h.Push(3);
    ExpectHistory(h.Undo(), 3);
    ExpectHistory(h.Undo(), 2);
    ExpectHistory(h.Undo(), 1);
    h.Clear();
    h.hasGroupInterval = false;
    h.Push(1);
    h.Push(2);
    h.Undo();
    h.StartGrouping();
    h.Push(3);
    h.EndGrouping();
    ExpectHistory(h.Undo(), 3, 1);
    h.Clear();
    h.Push(1);
    h.Push(2);
    h.Undo();
    h.Push(3);
    utassert(!h.CanRedo() && h.Redo().len == 0);
    h.Clear();
    h.SetIgnoring(true);
    h.Push(1);
    utassert(h.IsIgnoring() && !h.CanUndo() && h.Undo().len == 0);
    h.SetIgnoring(false);
    h.Push(1);
    h.Undo();
    h.Clear();
    utassert(!h.CanUndo() && !h.CanRedo());
    h.MaxUndos(2);
    h.Push(1);
    h.Push(2);
    h.Push(3);
    ExpectHistory(h.Undo(), 3);
    ExpectHistory(h.Undo(), 2);
    utassert(h.Undo().len == 0);
    h.Clear();
    h.MaxUndos(1000);
    h.Push(1);
    h.Push(2);
    h.Push(3);
    h.MaxUndos(2);
    ExpectHistory(h.Undo(), 3);
    ExpectHistory(h.Undo(), 2);
    utassert(h.Undo().len == 0);
    h.Clear();
    h.MaxUndos(1000);
    h.Push(1);
    h.Push(2);
    h.Push(3);
    h.Undo();
    h.MaxUndos(1);
    ExpectHistory(h.Redo(), 3);
    ExpectHistory(h.Undo(), 3);
    utassert(h.Undo().len == 0);
    h.Clear();
    h.Push(1);
    h.Undo();
    h.MaxUndos(0);
    utassert(h.Redo().len == 0 && h.CanRedo());
    h.Push(2);
    utassert(!h.CanUndo() && h.CanRedo());
    h.MaxUndos(1);
    ExpectHistory(h.Redo(), 1);
    h.Clear();
    h.MaxUndos(0);
    h.Push(1);
    utassert(!h.CanUndo() && h.Undo().len == 0);
}
void TestHistory() {
    NavigationHistory();
    TransactionHistory();
}
