/* Ported from rust_i18n's side of crates/ui: the catalogue in
 * crates/ui/locales/ui.yml, the locale in force, and what `t!(key)` answers.
 *
 * The table itself is generated by cmd/gen-locale-data.ts, so what is worth
 * pinning is the lookup around it: the fallback to English, an unknown key
 * answering with itself, and the ordering the binary search rests on. */

#include "Test.h"

using namespace gpui;
using namespace gpui::component;

// English is the fallback and the language the keys are written in, so it is
// first; the story adds French to the same keys, so it is last.
static void TheCatalogueLeadsWithEnglish() {
    utassert(LocaleCount() >= 2);
    utassert(base::StrEq(LocaleAt(0), StrL("en")));
    utassert(LocaleIndex(StrL("en")) == 0);
    utassert(LocaleIndex(StrL("zh-CN")) > 0);
    utassert(LocaleIndex(StrL("fr")) > 0);
    utassert(LocaleIndex(StrL("kl")) == -1);
    utassert(len(LocaleAt(-1)) == 0);
    utassert(len(LocaleAt(LocaleCount())) == 0);
}

// set_locale takes a locale the catalogue has and nothing else: a typo that
// took would blank every label in the window.
static void OnlyAKnownLocaleTakes() {
    utassert(base::StrEq(LocaleNow(), StrL("en")));
    utassert(LocaleSet(StrL("zh-CN")));
    utassert(base::StrEq(LocaleNow(), StrL("zh-CN")));
    utassert(!LocaleSet(StrL("kl")));
    utassert(base::StrEq(LocaleNow(), StrL("zh-CN")));
    utassert(!LocaleSet(Str{}));
    utassert(base::StrEq(LocaleNow(), StrL("zh-CN")));
    utassert(LocaleSet(StrL("en")));
}

// t!("Dialog.ok"), and the same key again with the locale moved.
static void AKeyAnswersInTheLocaleInForce() {
    utassert(LocaleSet(StrL("en")));
    utassert(base::StrEq(Tr("Dialog.ok"), StrL("OK")));
    utassert(base::StrEq(Tr("Calendar.month.August"), StrL("August")));
    utassert(base::StrEq(Tr("Pagination.previous"), StrL("Previous")));

    utassert(LocaleSet(StrL("fr")));
    utassert(base::StrEq(Tr("Calendar.month.August"), StrL("Août")));
    // The story's file is where that French came from; the component's own
    // file has no French for this one, so it falls back to English rather
    // than showing the key.
    utassert(base::StrEq(Tr("Dialog.ok"), StrL("OK")));

    utassert(LocaleSet(StrL("zh-CN")));
    utassert(base::StrEq(Tr("Calendar.week.0"), StrL("日")));
    utassert(base::StrEq(Tr("Dock.Zoom In"), StrL("放大")));
    utassert(LocaleSet(StrL("en")));
}

// A key nothing translates answers with itself, which is what rust_i18n does:
// a missing translation reads as `Dialog.nope` on screen rather than as an
// empty label nobody notices.
static void AnUnknownKeyAnswersWithItself() {
    utassert(base::StrEq(Tr("Dialog.nope"), StrL("Dialog.nope")));
    utassert(Tr(nullptr).len == 0);
    utassert(Tr("").len == 0);
}

// The generator writes the rows sorted, which is what the lookup's binary
// search rests on. A regenerate that stopped sorting would answer null for
// half the catalogue, and only for some of the keys.
static void TheRowsAreSorted() {
    int n = LocaleRowCount();
    utassert(n > 40);
    for (int i = 1; i < n; i++) {
        utassert(base::StrCmp(Str(LocaleRowAt(i - 1)->key),
                              Str(LocaleRowAt(i)->key)) < 0);
    }
    // And every row has the English the fallback needs.
    for (int i = 0; i < n; i++) {
        utassert(LocaleRowAt(i)->values[0] != nullptr);
    }
    utassert(LocaleRowAt(-1) == nullptr && LocaleRowAt(n) == nullptr);
}

void TestI18n() {
    TestSuite("i18n");
    TheCatalogueLeadsWithEnglish();
    OnlyAKnownLocaleTakes();
    AKeyAnswersInTheLocaleInForce();
    AnUnknownKeyAnswersWithItself();
    TheRowsAreSorted();
}
