#ifndef GPUI_UI_LIB_H_
#define GPUI_UI_LIB_H_
/* Themed gpui-kit façade — crates/ui/src */

#include "ui/accordion.h"
#include "ui/alert.h"
#include "ui/attachment.h"
#include "ui/avatar.h"
#include "ui/badge.h"
#include "ui/bubble.h"
#include "ui/breadcrumb.h"
#include "ui/button.h"
#include "ui/carousel.h"
#include "ui/chart.h"
#include "ui/checkbox.h"
#include "ui/clipboard.h"
#include "ui/collapsible.h"
#include "ui/color_picker.h"
#include "ui/combobox.h"
#include "ui/command.h"
#include "ui/component_traits.h"
#include "ui/sizing.h"
#include "ui/time.h"
#include "ui/description_list.h"
#include "ui/dialog.h"
#include "ui/dock.h"
#include "ui/tiles.h"
#include "ui/inspector.h"
#include "ui/form.h"
#include "ui/global_state.h"
#include "ui/group_box.h"
#include "ui/highlighter.h"
#include "ui/history.h"
#include "ui/hover_card.h"
#include "ui/i18n.h"
#include "ui/icon.h"
#include "ui/index_path.h"
#include "ui/input.h"
#include "ui/kbd.h"
#include "ui/label.h"
#include "ui/link.h"
#include "ui/list.h"
#include "ui/marker.h"
#include "ui/menu.h"
#include "ui/message.h"
#include "ui/message_scroller.h"
#include "ui/native_menu.h"
#include "ui/notification.h"
#include "ui/pagination.h"
#include "ui/plot.h"
#include "ui/popover.h"
#include "ui/progress.h"
#include "ui/radio.h"
#include "ui/rating.h"
#include "ui/resizable.h"
#include "ui/root.h"
#include "ui/scroll.h"
#include "ui/searchable_list.h"
#include "ui/select.h"
#include "ui/separator.h"
#include "ui/setting.h"
#include "ui/sheet.h"
#include "ui/sidebar.h"
#include "ui/shimmer.h"
#include "ui/skeleton.h"
#include "ui/slider.h"
#include "ui/spinner.h"
#include "ui/status_bar.h"
#include "ui/styled.h"
#include "ui/stepper.h"
#include "ui/switch.h"
#include "ui/tab.h"
#include "ui/table.h"
#include "ui/tag.h"
#include "ui/text.h"
#include "ui/theme.h"
#include "ui/title_bar.h"
#include "ui/tooltip.h"
#include "ui/tree.h"
#include "ui/virtual_list.h"
#include "ui/window_border.h"
#include "ui/window_ext.h"

namespace gpui {
namespace component {

// crates/ui/src/lib.rs::init: themed infrastructure, then gpui-base, then
// the modules with action bindings or system callbacks.
void Init(App* app);

} // namespace component
} // namespace gpui
#endif // GPUI_UI_LIB_H_
