/* Generated by cmd/gen-locale-data.ts — do not edit.

   The catalogue rust_i18n loads: crates/component/locales/ui.yml, plus the
   French the story's own file adds to the same keys. One row per key,
   sorted, with one string per locale and a null where the catalogue has
   nothing — the lookup falls back to English there. */

#include "ui/i18n.h"

namespace gpui {

namespace component {

extern const char* const kLocaleNames[] = {"en",    "zh-CN", "zh-HK",
                                           "zh-TW", "it",    "fr"};
extern const int kLocaleCount = 6;

static const char* const kV_Calendar_month_April[] = {
    "April", "四月", "四月", "四月", "Aprile", "Avril"};
static const char* const kV_Calendar_month_August[] = {
    "August", "八月", "八月", "八月", "Agosto", "Août"};
static const char* const kV_Calendar_month_December[] = {
    "December", "十二月", "十二月", "十二月", "Dicembre", "Décembre"};
static const char* const kV_Calendar_month_February[] = {
    "February", "二月", "二月", "二月", "Febbraio", "Février"};
static const char* const kV_Calendar_month_January[] = {
    "January", "一月", "一月", "一月", "Gennaio", "Janvier"};
static const char* const kV_Calendar_month_July[] = {
    "July", "七月", "七月", "七月", "Luglio", "Juillet"};
static const char* const kV_Calendar_month_June[] = {"June", "六月",   "六月",
                                                     "六月", "Giugno", "Juin"};
static const char* const kV_Calendar_month_March[] = {"March", "三月",  "三月",
                                                      "三月",  "Marzo", "Mars"};
static const char* const kV_Calendar_month_May[] = {"May",  "五月",   "五月",
                                                    "五月", "Maggio", "Mai"};
static const char* const kV_Calendar_month_November[] = {
    "November", "十一月", "十一月", "十一月", "Novembre", "Novembre"};
static const char* const kV_Calendar_month_October[] = {
    "October", "十月", "十月", "十月", "Ottobre", "Octobre"};
static const char* const kV_Calendar_month_September[] = {
    "September", "九月", "九月", "九月", "Settembre", "Septembre"};
static const char* const kV_Calendar_week_0[] = {"Su", "日", "日",
                                                 "日", "Do", "Di"};
static const char* const kV_Calendar_week_1[] = {"Mo", "一", "一",
                                                 "一", "Lu", "Lu"};
static const char* const kV_Calendar_week_2[] = {"Tu", "二", "二",
                                                 "二", "Ma", "Ma"};
static const char* const kV_Calendar_week_3[] = {"We", "三", "三",
                                                 "三", "Me", "Me"};
static const char* const kV_Calendar_week_4[] = {"Th", "四", "四",
                                                 "四", "Gi", "Je"};
static const char* const kV_Calendar_week_5[] = {"Fr", "五", "五",
                                                 "五", "Ve", "Ve"};
static const char* const kV_Calendar_week_6[] = {"Sa", "六", "六",
                                                 "六", "Sa", "Sa"};
static const char* const kV_ColorPicker_Alpha[] = {"Alpha",  "透明度", "透明度",
                                                   "透明度", "Alfa",   nullptr};
static const char* const kV_ColorPicker_HSLA[] = {"HSLA", "HSLA", "HSLA",
                                                  "HSLA", "HSLA", nullptr};
static const char* const kV_ColorPicker_Hue[] = {"Hue",  "色相",     "色相",
                                                 "色相", "Tonalità", nullptr};
static const char* const kV_ColorPicker_Lightness[] = {
    "Lightness", "亮度", "亮度", "亮度", "Luminosità", nullptr};
static const char* const kV_ColorPicker_Palette[] = {
    "Palette", "调色板", "調色板", "調色盤", "Tavolozza", nullptr};
static const char* const kV_ColorPicker_Saturation[] = {
    "Saturation", "饱和度", "飽和度", "飽和度", "Saturazione", nullptr};
static const char* const kV_ComboBox_empty[] = {"No results",       "暂无数据",
                                                "暫無數據",         "沒有結果",
                                                "Nessun risultato", nullptr};
static const char* const kV_ComboBox_placeholder[] = {
    "Please select", "请选择", "請選擇", "請選擇", "Seleziona", nullptr};
static const char* const kV_ComboBox_search_placeholder[] = {
    "Search...", "搜索...", "搜索...", "搜尋...", "Cerca...", nullptr};
static const char* const kV_Command_empty[] = {
    "No results found.",         "未找到结果。", "未找到結果。", "未找到結果。",
    "Nessun risultato trovato.", nullptr};
static const char* const kV_Command_placeholder[] = {
    "Type a command or search...",
    "输入命令或搜索...",
    "輸入命令或搜尋...",
    "輸入命令或搜尋...",
    "Digita un comando o cerca...",
    nullptr};
static const char* const kV_DatePicker_placeholder[] = {
    "Select date", "选择日期",       "選擇日期",
    "選取日期",    "Seleziona data", "Sélectionner une date"};
static const char* const kV_Dialog_cancel[] = {"Cancel", "取消",    "取消",
                                               "取消",   "Annulla", nullptr};
static const char* const kV_Dialog_ok[] = {"OK",   "确定", "確定",
                                           "確定", "OK",   nullptr};
static const char* const kV_Dock_Close[] = {"Close", "关闭",   "關閉",
                                            "關閉",  "Chiudi", nullptr};
static const char* const kV_Dock_Collapse[] = {"Collapse", "隐藏",     "隱藏",
                                               "收合",     "Nascondi", nullptr};
static const char* const kV_Dock_Expand[] = {"Expand", "展开",    "展開",
                                             "展開",   "Espandi", nullptr};
static const char* const kV_Dock_Unnamed[] = {"Unnamed", "未命名",     "未命名",
                                              "未命名",  "Senza nome", nullptr};
static const char* const kV_Dock_Zoom_In[] = {"Zoom In", "放大",    "放大",
                                              "放大",    "Zoom In", nullptr};
static const char* const kV_Dock_Zoom_Out[] = {"Zoom Out", "缩小",     "縮小",
                                               "縮小",     "Zoom Out", nullptr};
static const char* const kV_Input_Copy[] = {"Copy", "复制",  "複製",
                                            "複製", nullptr, nullptr};
static const char* const kV_Input_Cut[] = {"Cut",  "剪切",  "剪切",
                                           "剪下", nullptr, nullptr};
static const char* const kV_Input_Decrement[] = {"Decrement", "减少",  "減少",
                                                 "減少",      nullptr, nullptr};
static const char* const kV_Input_Go_to_Definition[] = {
    "Go to Definition", "跳转到定义", "跳轉到定義",
    "前往定義",         nullptr,      nullptr};
static const char* const kV_Input_Increment[] = {"Increment", "增加",  "增加",
                                                 "增加",      nullptr, nullptr};
static const char* const kV_Input_Paste[] = {"Paste", "粘贴",  "貼上",
                                             "貼上",  nullptr, nullptr};
static const char* const kV_Input_Replace[] = {"Replace", "替换",  "替換",
                                               "取代",    nullptr, nullptr};
static const char* const kV_Input_Replace_All[] = {
    "Replace All", "全部替换", "全部替換", "全部取代", nullptr, nullptr};
static const char* const kV_Input_Select_All[] = {
    "Select All", "全选", "全選", "全選", nullptr, nullptr};
static const char* const kV_Input_Show_Code_Actions[] = {
    "Show Code Actions", "显示代码操作", "顯示代碼操作",
    "顯示程式碼動作",    nullptr,        nullptr};
static const char* const kV_List_search_placeholder[] = {
    "Search...", "搜索...", "搜索...", "搜尋...", "Ricerca...", nullptr};
static const char* const kV_Pagination_next[] = {"Next",   "下一页", "下一頁",
                                                 "下一頁", nullptr,  nullptr};
static const char* const kV_Pagination_previous[] = {
    "Previous", "上一页", "上一頁", "上一頁", nullptr, nullptr};
static const char* const kV_Select_placeholder[] = {
    "Please select", "请选择", "請選擇", "請選擇", "Seleziona", nullptr};
static const char* const kV_Settings_Reset_All[] = {
    "Reset All", "重置全部", "重置全部", "全部重設", "Resetta Tutto", nullptr};
static const char* const kV_Settings_search_placeholder[] = {
    "Search...", "搜索...", "搜索...", "搜尋...", "Ricerca...", nullptr};

extern const LocaleRow kLocaleRows[] = {
    {"Calendar.month.April", kV_Calendar_month_April},
    {"Calendar.month.August", kV_Calendar_month_August},
    {"Calendar.month.December", kV_Calendar_month_December},
    {"Calendar.month.February", kV_Calendar_month_February},
    {"Calendar.month.January", kV_Calendar_month_January},
    {"Calendar.month.July", kV_Calendar_month_July},
    {"Calendar.month.June", kV_Calendar_month_June},
    {"Calendar.month.March", kV_Calendar_month_March},
    {"Calendar.month.May", kV_Calendar_month_May},
    {"Calendar.month.November", kV_Calendar_month_November},
    {"Calendar.month.October", kV_Calendar_month_October},
    {"Calendar.month.September", kV_Calendar_month_September},
    {"Calendar.week.0", kV_Calendar_week_0},
    {"Calendar.week.1", kV_Calendar_week_1},
    {"Calendar.week.2", kV_Calendar_week_2},
    {"Calendar.week.3", kV_Calendar_week_3},
    {"Calendar.week.4", kV_Calendar_week_4},
    {"Calendar.week.5", kV_Calendar_week_5},
    {"Calendar.week.6", kV_Calendar_week_6},
    {"ColorPicker.Alpha", kV_ColorPicker_Alpha},
    {"ColorPicker.HSLA", kV_ColorPicker_HSLA},
    {"ColorPicker.Hue", kV_ColorPicker_Hue},
    {"ColorPicker.Lightness", kV_ColorPicker_Lightness},
    {"ColorPicker.Palette", kV_ColorPicker_Palette},
    {"ColorPicker.Saturation", kV_ColorPicker_Saturation},
    {"ComboBox.empty", kV_ComboBox_empty},
    {"ComboBox.placeholder", kV_ComboBox_placeholder},
    {"ComboBox.search_placeholder", kV_ComboBox_search_placeholder},
    {"Command.empty", kV_Command_empty},
    {"Command.placeholder", kV_Command_placeholder},
    {"DatePicker.placeholder", kV_DatePicker_placeholder},
    {"Dialog.cancel", kV_Dialog_cancel},
    {"Dialog.ok", kV_Dialog_ok},
    {"Dock.Close", kV_Dock_Close},
    {"Dock.Collapse", kV_Dock_Collapse},
    {"Dock.Expand", kV_Dock_Expand},
    {"Dock.Unnamed", kV_Dock_Unnamed},
    {"Dock.Zoom In", kV_Dock_Zoom_In},
    {"Dock.Zoom Out", kV_Dock_Zoom_Out},
    {"Input.Copy", kV_Input_Copy},
    {"Input.Cut", kV_Input_Cut},
    {"Input.Decrement", kV_Input_Decrement},
    {"Input.Go to Definition", kV_Input_Go_to_Definition},
    {"Input.Increment", kV_Input_Increment},
    {"Input.Paste", kV_Input_Paste},
    {"Input.Replace", kV_Input_Replace},
    {"Input.Replace All", kV_Input_Replace_All},
    {"Input.Select All", kV_Input_Select_All},
    {"Input.Show Code Actions", kV_Input_Show_Code_Actions},
    {"List.search_placeholder", kV_List_search_placeholder},
    {"Pagination.next", kV_Pagination_next},
    {"Pagination.previous", kV_Pagination_previous},
    {"Select.placeholder", kV_Select_placeholder},
    {"Settings.Reset All", kV_Settings_Reset_All},
    {"Settings.search_placeholder", kV_Settings_search_placeholder},
};
extern const int kLocaleRowCount = 55;

} // namespace component
} // namespace gpui
