// Format this repo's C++ (clang-format) and TypeScript (prettier).
//
//   bun cmd/format.ts                  # every C++ root + cmd/*.ts
//   bun cmd/format.ts -ts              # prettier only (cmd/*.ts)
//   bun cmd/format.ts -cpp             # clang-format only
//   bun cmd/format.ts src/gpui/gpui.cpp cmd/build.ts

import { $, Glob } from "bun";
import { existsSync } from "node:fs";
import { cpus } from "node:os";
import { dirname, extname, join, resolve } from "node:path";

const root = resolve(dirname(Bun.main), "..");
process.chdir(root);

const cppExt = new Set([".cpp", ".h", ".c", ".hpp"]);
const tsExt = new Set([".ts", ".js", ".json", ".md"]);

// Hand-written C++ lives in these roots. Recursive so a new crate, example
// subdirectory, or test file is formatted without updating this list. Never
// glob `.work/` or `out/`.
const cppGlobs = ["src", "examples", "tests", "bench", "gpui_shell"].map((dir) => `${dir}/**/*.{cpp,h,c,hpp}`);

const tsGlobs = ["cmd/*.ts"];

// Generated files: the generator lays them out itself. clang-format would
// unpack the byte rows in the icon table into one byte a line, and wrap the
// source-sha256 marker that cmd/build.ts uses to reject stale shader bytecode.
const generated = new Set(["src/gpui/asset_icons.cpp", "src/gpui/paintgpu_shaders_win.cpp"]);

function skipCpp(path: string): boolean {
  if (generated.has(path)) {
    return true;
  }
  // QuickJS-NG is vendored upstream C, regenerated by cmd/update-quickjs.ts.
  return path.startsWith("src/quickjs/");
}

async function globFiles(patterns: string[]): Promise<string[]> {
  const files: string[] = [];
  for (const pattern of patterns) {
    const glob = new Glob(pattern);
    for await (const file of glob.scan({ cwd: root, dot: false })) {
      files.push(file.replaceAll("\\", "/"));
    }
  }
  return files;
}

function ensureLf(text: string): string {
  return text.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
}

function findClangFormat(): string {
  if (process.platform !== "win32") {
    const found = Bun.spawnSync(["xcrun", "--find", "clang-format"], {
      cwd: root,
      stdout: "pipe",
      stderr: "pipe",
    });
    if ((found.exitCode ?? 1) === 0) {
      const path = new TextDecoder().decode(found.stdout).trim();
      if (path) {
        return path;
      }
    }
    return "clang-format";
  }
  const rels = [String.raw`VC\Tools\Llvm\bin\clang-format.exe`, String.raw`VC\Tools\Llvm\x64\bin\clang-format.exe`];
  const editions = ["Community", "Professional", "Enterprise"];
  const programFiles = process.env["ProgramFiles"] ?? String.raw`C:\Program Files`;
  for (const ver of ["2022", "18"]) {
    for (const edition of editions) {
      const vsRoot = join(programFiles, "Microsoft Visual Studio", ver, edition);
      for (const rel of rels) {
        const p = join(vsRoot, rel);
        if (existsSync(p)) {
          return p;
        }
      }
    }
  }
  return "clang-format.exe";
}

async function formatCpp(clangFormatPath: string, path: string): Promise<void> {
  const compat = process.platform === "darwin" ? ["--Wno-error=unknown"] : [];
  await $`${clangFormatPath} ${compat} -i -style=file ${path}`.quiet();
  const text = await Bun.file(path).text();
  const lf = ensureLf(text);
  if (lf !== text) {
    await Bun.write(path, lf);
  }
}

async function formatTs(paths: string[]): Promise<void> {
  if (paths.length === 0) {
    return;
  }
  const r = Bun.spawnSync(["bunx", "prettier", "--write", ...paths], {
    cwd: root,
    stdout: "inherit",
    stderr: "inherit",
  });
  if ((r.exitCode ?? 1) !== 0) {
    throw new Error("prettier failed");
  }
}

async function mapPool<T>(items: T[], limit: number, fn: (item: T) => Promise<void>): Promise<void> {
  let i = 0;
  async function next(): Promise<void> {
    while (i < items.length) {
      const idx = i++;
      await fn(items[idx]!);
    }
  }
  const n = Math.min(limit, items.length);
  await Promise.all(Array.from({ length: n }, () => next()));
}

const argv = Bun.argv.slice(2);
const paths: string[] = [];
let wantCpp = false;
let wantTs = false;
for (const raw of argv) {
  if (raw === "-ts" || raw === "--ts") {
    wantTs = true;
    continue;
  }
  if (raw === "-cpp" || raw === "--cpp") {
    wantCpp = true;
    continue;
  }
  if (raw.startsWith("-")) {
    console.error(`unknown option: ${raw}`);
    console.error("usage: bun cmd/format.ts [-ts] [-cpp] [paths...]");
    process.exit(1);
  }
  paths.push(raw);
}
if (!wantCpp && !wantTs) {
  wantCpp = true;
  wantTs = true;
}

let cppFiles: string[] = [];
let tsFiles: string[] = [];
if (paths.length > 0) {
  for (const raw of paths) {
    const ext = extname(raw).toLowerCase();
    const norm = raw.replaceAll("\\", "/");
    if (cppExt.has(ext)) {
      if (wantCpp && !skipCpp(norm)) {
        cppFiles.push(norm);
      }
    } else if (tsExt.has(ext)) {
      if (wantTs) {
        tsFiles.push(norm);
      }
    } else {
      console.error(`skip (unknown type): ${raw}`);
    }
  }
} else {
  if (wantCpp) {
    cppFiles = (await globFiles(cppGlobs)).filter((p) => !skipCpp(p));
  }
  if (wantTs) {
    tsFiles = await globFiles(tsGlobs);
  }
}

if (wantCpp) {
  const clangFormatPath = findClangFormat();
  console.log(`using '${clangFormatPath}'`);
  await mapPool(cppFiles, cpus().length, (p) => formatCpp(clangFormatPath, p));
  console.log(`formatted ${cppFiles.length} C++ files`);
}

if (wantTs && tsFiles.length > 0) {
  await formatTs(tsFiles);
  console.log(`formatted ${tsFiles.length} TS/JSON/MD files`);
}
