// Generates src/ui/theme_data.cpp from the two JSON files the Rust theme
// `include_str!`s: `default-colors.json`, the shadcn colour scales a theme
// file names its colours out of ("neutral-200", "red-500"), and
// `default-theme.json`, the palette every other theme is resolved against.
//
// Rust reads both at runtime because it can embed a file with one macro. Here
// they become a table and a string, so the values still come from upstream's
// files rather than from a hand transcription, and re-running this is how a
// later upstream checkin's palette lands.
//
//   bun cmd/gen-theme-data.ts
//
// It needs `.work/gpui-component` at the pinned SHA (`bun cmd/run.ts -versions`).

import { join } from "path";
import { readFileSync, writeFileSync } from "fs";

const root = join(import.meta.dir, "..");
const themeDir = join(root, ".work", "gpui-component", "crates", "component", "src", "theme");

// The 19 hues `ColorName::try_from` accepts, in its own order. `default-colors.json`
// also carries slate, zinc and stone, but no `ColorName` names them, so
// `ColorName::scale` could never reach them and neither can we.
const HUES = [
  "neutral",
  "gray",
  "red",
  "orange",
  "amber",
  "yellow",
  "lime",
  "green",
  "emerald",
  "teal",
  "cyan",
  "sky",
  "blue",
  "indigo",
  "violet",
  "purple",
  "fuchsia",
  "pink",
  "rose",
];

// The scales every hue carries, in ascending order. 500 is what an unknown
// scale falls back to, which the C++ side finds by looking it up like any other.
const SCALES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];

function hexToU32(hex: string): number {
  const h = hex.trim().replace(/^#/, "");
  if (h.length !== 6) throw new Error(`unexpected hex ${hex}`);
  return parseInt(h, 16);
}

function cLiteral(s: string): string {
  const escaped = s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
  return '"' + escaped + '"';
}

function main() {
  const colors = JSON.parse(readFileSync(join(themeDir, "default-colors.json"), "utf8"));
  const themeJson = readFileSync(join(themeDir, "default-theme.json"), "utf8");

  const out: string[] = [];
  out.push("/* Generated by cmd/gen-theme-data.ts — do not edit.");
  out.push("");
  out.push("   The two files crates/component/src/theme `include_str!`s: the shadcn colour");
  out.push("   scales a theme names its colours out of, and the default theme every");
  out.push("   other one is resolved against. Re-run the generator to take a later");
  out.push("   upstream palette. */");
  out.push("");
  out.push('#include "ui/theme.h"');
  out.push("");
  out.push("namespace gpui {");
  out.push("");
  out.push("// ColorName, and the eleven scales each hue carries.");
  out.push("const ShadcnScale kShadcnScales[] = {");
  for (const hue of HUES) {
    const entries = colors[hue];
    if (!Array.isArray(entries)) throw new Error(`missing hue ${hue}`);
    const byScale = new Map<number, string>();
    for (const e of entries) byScale.set(e.scale, e.hex);
    const hexes = SCALES.map((s) => {
      const hex = byScale.get(s);
      if (!hex) throw new Error(`${hue} has no scale ${s}`);
      return "0x" + hexToU32(hex).toString(16).padStart(6, "0");
    });
    out.push(`    {"${hue}",`);
    out.push(`     {${hexes.slice(0, 6).join(", ")},`);
    out.push(`      ${hexes.slice(6).join(", ")}}},`);
  }
  out.push("};");
  out.push(`const int kNumShadcnScales = ${HUES.length};`);
  out.push("");
  out.push("// The scale numbers the eleven columns above stand for.");
  out.push(`const int kShadcnScaleNums[kNumShadcnColumns] = {${SCALES.join(", ")}};`);
  out.push("");
  out.push("// `stone`, which no ColorName can reach — a theme file may not name it —");
  out.push("// but the colour picker's palette grid is nine hues and stone is the first");
  out.push("// of them (color_picker.rs, color_palettes()).");
  out.push("const uint32_t kShadcnStone[kNumShadcnColumns] = {");
  {
    const entries = colors.stone;
    if (!Array.isArray(entries)) throw new Error("missing hue stone");
    const byScale = new Map<number, string>();
    for (const e of entries) byScale.set(e.scale, e.hex);
    const hexes = SCALES.map((sc) => {
      const hex = byScale.get(sc);
      if (!hex) throw new Error(`stone has no scale ${sc}`);
      return "0x" + hexToU32(hex).toString(16).padStart(6, "0");
    });
    out.push(`    ${hexes.slice(0, 6).join(", ")},`);
    out.push(`    ${hexes.slice(6).join(", ")}};`);
  }
  out.push("");
  out.push("// `black` and `white`, which are not a scale and are named on their own.");
  out.push(`const uint32_t kShadcnBlack = 0x${hexToU32(colors.black.hex).toString(16).padStart(6, "0")};`);
  out.push(`const uint32_t kShadcnWhite = 0x${hexToU32(colors.white.hex).toString(16).padStart(6, "0")};`);
  out.push("");
  out.push("// default-theme.json, verbatim. One literal per line, because MSVC caps a");
  out.push("// single string literal at 16380 bytes and this file is close enough to it");
  out.push("// that an upstream addition would push it over.");
  out.push("const char* const kDefaultThemeJson =");
  const lines = themeJson.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const last = i === lines.length - 1;
    out.push(`    ${cLiteral(lines[i] + (last ? "" : "\n"))}${last ? ";" : ""}`);
  }
  out.push("");
  out.push("} // namespace gpui");
  out.push("");

  const dest = join(root, "src", "ui", "theme_data.cpp");
  writeFileSync(dest, out.join("\n"), "utf8");
  console.log(`wrote ${dest}: ${HUES.length} hues, ${themeJson.length} bytes of default theme`);
}

main();
