// Generates src/ui/locale_data.cpp from the two locale files rust_i18n loads:
// `crates/component/locales/ui.yml`, the component strings, and
// `crates/story/locales/ui.yml`, which the story adds French to.
//
// Rust reads them at build time through the `i18n!` macro. Here they become a
// table, so the translations still come from upstream's own files rather than
// from a hand transcription, and a later checkin's wording lands by re-running
// this.
//
//   bun cmd/gen-locale-data.ts
//
// It needs `.work/gpui-component` at the pinned SHA (`bun cmd/run.ts -versions`).
//
// The parse is not a YAML parser and does not need to be: both files are
// three levels of plain `key:` lines with a scalar at the bottom, and the
// only quoting upstream uses is a double-quoted value. Anything else in the
// file is a reason to look at it rather than to widen this.

import { join } from "path";
import { readFileSync, writeFileSync } from "fs";

const root = join(import.meta.dir, "..");
const upstream = join(root, ".work", "gpui-component");

// English first: it is the fallback, and the language the keys are written
// in. The rest in the order they first appear across the two files.
const LOCALES = ["en", "zh-CN", "zh-HK", "zh-TW", "it", "fr"];

type Catalogue = Map<string, Map<string, string>>;

function unquote(value: string): string {
  const v = value.trim();
  if (v.length >= 2 && v.startsWith('"') && v.endsWith('"')) {
    return v.slice(1, -1).replace(/\\"/g, '"');
  }
  return v;
}

// `gpui_component:` in the story's file is rust_i18n's crate namespace, not a
// section: the keys under it are the same keys the ui crate declares, which is
// how the story adds a locale to strings it does not own.
function readCatalogue(path: string, into: Catalogue) {
  const text = readFileSync(path, "utf8").replace(/\r\n/g, "\n");
  let section = "";
  let key = "";
  let base = 0;
  for (const raw of text.split("\n")) {
    if (!raw.trim() || raw.trim().startsWith("#") || raw.startsWith("_version")) {
      continue;
    }
    const indent = raw.length - raw.trimStart().length;
    const line = raw.trim();
    if (line === "gpui_component:") {
      // rust_i18n's crate namespace: the story's file nests everything one
      // level deeper under it, so where a section starts is read off the
      // file rather than assumed.
      base = 2;
      continue;
    }
    const level = (indent - base) / 2;
    if (level < 0 || level > 2 || !Number.isInteger(level)) {
      throw new Error(`unexpected indent in ${path}: ${raw}`);
    }
    const colon = line.indexOf(":");
    if (colon < 0) {
      throw new Error(`unreadable line in ${path}: ${raw}`);
    }
    const name = line.slice(0, colon);
    const value = line.slice(colon + 1).trim();
    if (level === 0) {
      section = name;
      key = "";
    } else if (level === 1) {
      key = name;
    } else {
      if (!section || !key) {
        throw new Error(`value before its key in ${path}: ${raw}`);
      }
      if (!LOCALES.includes(name)) {
        throw new Error(`unknown locale ${name} in ${path}`);
      }
      const full = `${section}.${key}`;
      let row = into.get(full);
      if (!row) {
        row = new Map();
        into.set(full, row);
      }
      row.set(name, unquote(value));
    }
  }
}

const catalogue: Catalogue = new Map();
readCatalogue(join(upstream, "crates", "component", "locales", "ui.yml"), catalogue);
readCatalogue(join(upstream, "crates", "story", "locales", "ui.yml"), catalogue);

const keys = [...catalogue.keys()].sort();
const missingEnglish = keys.filter((k) => !catalogue.get(k)!.has("en"));
if (missingEnglish.length > 0) {
  // English is what the lookup falls back to, so a key without one would be
  // a label that reads as its own key in five locales out of six.
  throw new Error(`no English for: ${missingEnglish.join(", ")}`);
}

function cstr(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

const out: string[] = [];
out.push("/* Generated by cmd/gen-locale-data.ts — do not edit.");
out.push("");
out.push("   The catalogue rust_i18n loads: crates/component/locales/ui.yml, plus the");
out.push("   French the story's own file adds to the same keys. One row per key,");
out.push("   sorted, with one string per locale and a null where the catalogue has");
out.push("   nothing — the lookup falls back to English there. */");
out.push("");
out.push('#include "ui/i18n.h"');
out.push("");
out.push("namespace gpui {");
out.push("");
out.push("namespace component {");
out.push("");
out.push("extern const char* const kLocaleNames[] = {");
out.push(`    ${LOCALES.map(cstr).join(", ")}};`);
out.push(`extern const int kLocaleCount = ${LOCALES.length};`);
out.push("");
for (const key of keys) {
  const row = catalogue.get(key)!;
  const ident = key.replace(/[^A-Za-z0-9]/g, "_");
  const values = LOCALES.map((l) => (row.has(l) ? cstr(row.get(l)!) : "nullptr"));
  out.push(`static const char* const kV_${ident}[] = {`);
  out.push(`    ${values.join(", ")}};`);
}
out.push("");
out.push("extern const LocaleRow kLocaleRows[] = {");
for (const key of keys) {
  const ident = key.replace(/[^A-Za-z0-9]/g, "_");
  out.push(`    {${cstr(key)}, kV_${ident}},`);
}
out.push("};");
out.push(`extern const int kLocaleRowCount = ${keys.length};`);
out.push("");
out.push("} // namespace component");
out.push("} // namespace gpui");
out.push("");

const dest = join(root, "src", "ui", "locale_data.cpp");
writeFileSync(dest, out.join("\n"), "utf8");
console.log(`wrote ${dest}: ${keys.length} keys x ${LOCALES.length} locales`);
