// Regenerate the declaration text embedded by the C++ shell runtime from the
// gpui-shell crate pinned in cmd/run.ts. Ordinary builds use the checked-in
// generated source and never invoke Cargo.
//
// Two files come out of it:
//
//   src/shell/typings_data.cpp        what `gpui-shell types` writes: the
//                                     runtime's declarations with an empty
//                                     component catalog. The C++ shell splices
//                                     its own catalog's declarations into it,
//                                     the way typings.rs does.
//   tests/ComponentShellTypesData.cpp the `declare module "gpui-component"`
//                                     block and the `Element` union that
//                                     `gpui-component-shell types` writes, which
//                                     the tests hold the C++ catalog to.
//
// `-check` regenerates both into memory and fails if either differs.

import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { gpuiComponent } from "./run.ts";

const root = resolve(import.meta.dir, "..");
const checkout = join(root, gpuiComponent.dir);
const generatedDir = join(root, ".work", "shell-types-generated");
const componentDir = join(root, ".work", "component-shell-types-generated");
const outputPath = join(root, "src", "shell", "typings_data.cpp");
const testOutputPath = join(root, "tests", "ComponentShellTypesData.cpp");
const check = process.argv.slice(2).includes("-check");

function run(args: string[], cwd = root): void {
  const result = Bun.spawnSync(args, { cwd, stdout: "inherit", stderr: "inherit" });
  if ((result.exitCode ?? 1) !== 0) {
    throw new Error(`${args.join(" ")} failed with exit ${result.exitCode ?? 1}`);
  }
}

function generateDeclarations(pkg: string, bin: string | null, dir: string): string {
  if (!existsSync(join(checkout, ".git"))) {
    throw new Error(`missing ${gpuiComponent.dir}; run bun cmd/run.ts -versions first`);
  }
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  const binArgs = bin ? ["--bin", bin] : [];
  run(["cargo", "run", "-q", "-p", pkg, ...binArgs, "--", "types", dir], checkout);
  return readFileSync(join(dir, "gpui-kit.d.ts"), "utf8").replaceAll("\r\n", "\n").replaceAll("\r", "\n");
}

function chunks(source: string): string[] {
  const result: string[] = [];
  let chunk = "";
  for (const line of source.split(/(?<=\n)/)) {
    if (chunk.length > 0 && Buffer.byteLength(chunk + line, "utf8") > 12_000) {
      result.push(chunk);
      chunk = "";
    }
    chunk += line;
  }
  if (chunk.length > 0) result.push(chunk);
  return result;
}

const delimiter = "GPUI_DTS";

function rawStrings(prefix: string, source: string, lines: string[]): string[] {
  if (source.includes(`)${delimiter}\"`)) {
    throw new Error("gpui-kit.d.ts collides with the generated C++ raw-string delimiter");
  }
  const parts = chunks(source);
  const names: string[] = [];
  for (let i = 0; i < parts.length; i++) {
    const name = `${prefix}${i}`;
    lines.push(`static const char ${name}[] = R\"${delimiter}(${parts[i]})${delimiter}\";`);
    names.push(name);
  }
  return names;
}

function appendBody(names: string[], lines: string[]): void {
  for (const name of names) {
    lines.push(`    out->Append(Str(${name}, (int)sizeof(${name}) - 1));`);
  }
}

function cpp(source: string): string {
  const lines = [
    "// Generated by cmd/update-shell-types.ts from the pinned gpui-shell crate.",
    "// Do not edit this file by hand.",
    '#include "shell/typings.h"',
    "",
    "namespace gpui::shell {",
    "",
  ];
  const names = rawStrings("kShellTypes", source, lines);
  lines.push("", "void AppendBuiltinTypeDeclarations(StrBuilder* out) {");
  appendBody(names, lines);
  lines.push("}", "", "} // namespace gpui::shell", "");
  return lines.join("\n");
}

const componentModuleStart = 'declare module "gpui-component" {\n';
const componentModuleEnd = '\ndeclare module "gpui-shell" {\n';

// The `declare module "gpui-component"` block, through the blank line after
// its closing brace, and the registered half of the `Element` union.
function componentParts(full: string): { block: string; union: string } {
  const start = full.indexOf(componentModuleStart);
  const end = full.indexOf(componentModuleEnd, start);
  if (start < 0 || end < 0) throw new Error("gpui-component-shell types: no gpui-component module");
  const unionMatch = full.match(/\n {2}export type Element = NativeElement(.*);\n/);
  if (!unionMatch) throw new Error("gpui-component-shell types: no Element union");
  return { block: full.slice(start, end + 1), union: unionMatch[1] };
}

function testCpp(full: string): string {
  const { block, union } = componentParts(full);
  const lines = [
    "// Generated by cmd/update-shell-types.ts from the pinned",
    "// gpui-component-shell crate: what `gpui-component-shell types` writes for",
    "// the catalog, which ComponentShellTests.cpp holds the C++ catalog to.",
    "// Do not edit this file by hand.",
    '#include "Test.h"',
    "",
  ];
  const blockNames = rawStrings("kComponentModule", block, lines);
  const unionNames = rawStrings("kComponentUnion", union, lines);
  lines.push("", "void AppendRustComponentDeclarations(StrBuilder* out) {");
  appendBody(blockNames, lines);
  lines.push("}", "", "void AppendRustComponentElementUnion(StrBuilder* out) {");
  appendBody(unionNames, lines);
  lines.push("}", "");
  return lines.join("\n");
}

const bare = generateDeclarations("gpui-shell", null, generatedDir);
const full = generateDeclarations("gpui-component-shell", "gpui-component-shell", componentDir);
const generated = cpp(bare);
const generatedTest = testCpp(full);
if (check) {
  if (!existsSync(outputPath) || readFileSync(outputPath, "utf8") !== generated) {
    throw new Error("src/shell/typings_data.cpp is stale; run bun cmd/update-shell-types.ts");
  }
  if (!existsSync(testOutputPath) || readFileSync(testOutputPath, "utf8") !== generatedTest) {
    throw new Error("tests/ComponentShellTypesData.cpp is stale; run bun cmd/update-shell-types.ts");
  }
  console.log(`src/shell/typings_data.cpp and tests/ComponentShellTypesData.cpp match ${gpuiComponent.sha}`);
} else {
  writeFileSync(outputPath, generated, "utf8");
  writeFileSync(testOutputPath, generatedTest, "utf8");
  console.log(
    `generated src/shell/typings_data.cpp (${Buffer.byteLength(generated, "utf8")} bytes) and ` +
      `tests/ComponentShellTypesData.cpp (${Buffer.byteLength(generatedTest, "utf8")} bytes) from ${gpuiComponent.sha}`,
  );
}
