// Regenerate the declaration text embedded by the C++ shell runtime from the
// gpui-shell crate pinned in cmd/run.ts. Ordinary builds use the checked-in
// generated source and never invoke Cargo.

import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { gpuiComponent } from "./run.ts";

const root = resolve(import.meta.dir, "..");
const checkout = join(root, gpuiComponent.dir);
const generatedDir = join(root, ".work", "shell-types-generated");
const declarationPath = join(generatedDir, "gpui-kit.d.ts");
const outputPath = join(root, "src", "shell", "typings_data.cpp");
const check = process.argv.slice(2).includes("-check");

function run(args: string[], cwd = root): void {
  const result = Bun.spawnSync(args, { cwd, stdout: "inherit", stderr: "inherit" });
  if ((result.exitCode ?? 1) !== 0) {
    throw new Error(`${args.join(" ")} failed with exit ${result.exitCode ?? 1}`);
  }
}

function generateDeclarations(): string {
  if (!existsSync(join(checkout, ".git"))) {
    throw new Error(`missing ${gpuiComponent.dir}; run bun cmd/run.ts -versions first`);
  }
  rmSync(generatedDir, { recursive: true, force: true });
  mkdirSync(generatedDir, { recursive: true });
  run(["cargo", "run", "-p", "gpui-shell", "--", "types", generatedDir], checkout);
  return readFileSync(declarationPath, "utf8").replaceAll("\r\n", "\n").replaceAll("\r", "\n");
}

function chunks(source: string): string[] {
  const result: string[] = [];
  let chunk = "";
  for (const line of source.split(/(?<=\n)/)) {
    if (chunk.length > 0 && Buffer.byteLength(chunk + line, "utf8") > 12_000) {
      result.push(chunk);
      chunk = "";
    }
    chunk += line;
  }
  if (chunk.length > 0) result.push(chunk);
  return result;
}

function cpp(source: string): string {
  const delimiter = "GPUI_DTS";
  if (source.includes(`)${delimiter}\"`)) {
    throw new Error("gpui-kit.d.ts collides with the generated C++ raw-string delimiter");
  }
  const lines = [
    "// Generated by cmd/update-shell-types.ts from the pinned gpui-shell crate.",
    "// Do not edit this file by hand.",
    '#include "shell/typings.h"',
    "",
    "namespace gpui::shell {",
    "",
  ];
  const parts = chunks(source);
  for (let i = 0; i < parts.length; i++) {
    lines.push(`static const char kShellTypes${i}[] = R\"${delimiter}(${parts[i]})${delimiter}\";`);
  }
  lines.push("", "void AppendBuiltinTypeDeclarations(StrBuilder* out) {");
  for (let i = 0; i < parts.length; i++) {
    lines.push(`    out->Append(Str(kShellTypes${i}, (int)sizeof(kShellTypes${i}) - 1));`);
  }
  lines.push("}", "", "} // namespace gpui::shell", "");
  return lines.join("\n");
}

const source = generateDeclarations();
const generated = cpp(source);
if (check) {
  if (!existsSync(outputPath) || readFileSync(outputPath, "utf8") !== generated) {
    throw new Error("src/shell/typings_data.cpp is stale; run bun cmd/update-shell-types.ts");
  }
  console.log(`src/shell/typings_data.cpp matches gpui-shell at ${gpuiComponent.sha}`);
} else {
  writeFileSync(outputPath, generated, "utf8");
  console.log(
    `generated src/shell/typings_data.cpp (${Buffer.byteLength(generated, "utf8")} bytes, ` +
      `${Buffer.byteLength(source, "utf8")} declaration bytes) from ${gpuiComponent.sha}`,
  );
}
