/* Generated by cmd/update-win-shaders.ts. Do not edit.
   source-sha256: c96e624322fa9ce11a42798184fb87a26ff1a3a5687d8074959bd54a79acce11
   encoding: basE95 over printable ASCII space through ~ */

#include "gpui/paintgpu.h"

#if WIN_BACKEND_GPU
namespace gpui {
namespace gpuw {

extern const char kShaderVSQuad95[] = R"GPUI95(
.Ea8f{K?|Jb[:{q)0/^{X}I#t(   uUG +K"   D$  6v' 6vD!  ,<  3S2 +K"NkAEa! j*    M!  @   Kk!   f&2v:K&&``
.U   ]+c9TH    #   `   M-  +K$   8       ``'   %   !!  b"    8       `   j*    f"
.                        U5    $   Ee~lI3Z 0bh2}LuDDvoZO%  $$  +K7   !!            ^   (   &f)   8
.       ""  +KU       b"  j*    d$      Ss5v5v!   uu5vT5    D4  j*    "       +K#       4v5v@!  ``5v5
.v/   88/   (   A!      6v_       uu5vT5    2v5va"    I!  A!  b"        y%      Ss5v5v!   uu5vT5    9
.9  PP    !       #C$       4v5v@!  ``5v5v/   U53   4   `         X       uu5vT5    2v5va"  +K8>?Z4HY
.I\)= GAy>Fn%!'oG=# 8 @ b"                            =]! uU);l+X5uX7Me^oLOZm@00li\a 8.K7"00+K  (
.                             \"  q)9d(8MVU^K:n@*W.K"ie'l)  ((j*6v                            +KL!  9
.ELD~yxOrH^.~;holb1KU;OzZ3tL5$wgoZ.<        ,   $   r2#       5v5v_   Kk5v5v'   PP"N/B[.<)= OFd)= `.Y
.~Dv7"00+K  (                             \"  !i$i+-2KmW2EBvl[I$2KCiA@QEUIgT, J?NY  +K5       |\  +K5
.   (   M]  +K5   0   u]  +K5   8   >^  +K5   @   V^  +K5   H   H   A!+K!   & _?                    z
.:J   &9NS'k9s71eK77w-u5)gGSp0a\!Qn9x*,I4)#g5=932bbbU088ageTi!  `   +K    X       00  6v        A!" 6
.v(       b"  E%  6v    ]5  3Syg1Zv,e^}k3N>v'>k..E*W>S}b\RO+yY`r%<MF97  z:    $   t4      +K    8
.       ``#   z*            &   @   00""  f"  0       +K!   (   00, +KG!          ``    (   **  U5c
.   $       @@    &   %%  U50   "       ((    !   \   b"! @@        !!  z:    /   kK  U5        P   0
.0  6v10  kK  z:        P   00    *$  u5  00        8   I)  +K'   *R5`RrT^Zfto2EuUo%a68I/}>vU4_nd;]=$
.'@79A@   H " m5  z:c VvL U5k+rK      !   ;;  ( I)$     00    # A!^5`     00    P U5##n*E%    $   `(
.  EcD!!     $   $d  CKa5@ (   qQ! fv&6@ (   qQ! fv26@ 0   qQ! fv26@ 8   qQ! fv26@ @   qQ! fv26@ H
.   qQ! fva5@ P   qQ! fv&6@ P   qQ! fv26@ X   uU! KK!   T$  |xwv      $ "                 +Kuv  ww, 0
.     $$;K      $ " @   00            Kk! B") @     #C  !     H b"      % d$b `     z:A!"     ( ( b"
.  U5  z:4$E%    +KA 0     A!`     jJ  Kk/         h!@@(w%$r2|d, )%A!@   uUb"$ !   0 0     6v&u@
.     Cc  gwP 0     $$/K      znb"`   ``A!( "   d$  z*# $ "   fFZ5      f C!        6v, 88Q!I%    +K"
. 0 (   ` `     +K" "     m.# f&Xv`     &f  -Ka   @   b"b"      % $     vx# f&R ` @   00w 8v    0 (
.     =%  tt        U5& 00*"b"`   ``_#( "   ` @     55  Kk'         C @ (       kKa5@ (   3SK !     z
."b",L  U5    :"+Kzxwv+K!   _gF%    +K- M-@0r*E%    H%@ 0   TT" G7%$& \@71j*T%$ "   a!n*E%  6v6v  A!
.  >~tx      Q#``c!+(eEcS9 2*I%$$  +Kl*@ (   A!A!  *   xli"    Kk4 n.J@!!d$fS7v26@ @   M-` ,K    ( (
. +K  6v&u@     TT" G7%$& \@71j*T%$ %   a!n*E%  6v6v  $$  >~tx      Q#``c!+(eEcS9 2*E%A!  +Kl*@ (   A
.!A!  (   xli"        E%$"`     00@ -Ka   0   006!8v    4$6vGcA!7v!   z"b"    ``_#(     W7+KU5    :"+
.KEcD!,K#   !Qm*E%    ? E%5} 6jV$   ,   8       6v!   2   @   00    !
.                                   !!                b"
.                                                                                  )GPUI95";
extern const int kShaderVSQuadSize = 2536;
uint8_t kShaderVSQuadBytes[2536] = {};

extern const char kShaderPSQuad95[] = R"GPUI95(
.Ea8f(XP*W6{.XQ+o^ZEk)bk`5     l +K"   D$  00,   l"   P  PPi 6v"NkA'C! E%    -!  @   pp    C#5v\5##M-
.5   %|^|&%  @@    (   a!  88  6v!       ?_  @@                      (   A!  +KP   (   C#  +K    4v5v
.a"  U5    T   1Q! +K    4   b"  Kk5v5v7   A!  U5#   h(                        +K    (   TT;.pD1!+//G
.&zq$L\!]To.Br2ki=bdbI3U5# 6v!   **  ``            ``#       0       U5?       &v5vi*    4v5v@!    c
.   0   b"        \"      tt5v5v    &v5vi*    E+  j*    "   $   00"       5v5v_   Kk5v5v'   z:)   (
.   0   A!  6vF       &v5vi*    4v5v@!  6vq   h   A!  j*    N&      Ss5v5v!   uu5vT5    ,<  uU    "
.       .n#       4v5v@!  ``5v5v/   XXo<>dfxOTJn@@C]$MK:<voZ 26v! " 0                             >*
.  nn''K(GGB.-*-P*hS]P nbs]Vf3"wg  & ( A!                            NN  XX_<*qZ2f2]fX/rF5!GOREwV# 6v
.! " (                             p,  nn(b2\sc?.tEFA]SAd:"q)9d(8_X!QvULCTQ%j'kc7L%AWr =|%<#weyF0DRm$
.HV4]P/QDVQ;8L@X|a`G=+T-Y63\+  M-    "   J*      U5    ,       Kk!   M%          6v!   (   $$& 6v@
.   "       00    !   ""# #C(           $$  +K    (l! Q1$ +K        $$  ``    (l! E%" +K        ""  +
.K    $F  b"! @@        !!  z:    WH  Ww  U5        P   00  6v%$  u5  M-        8   ((  6v%$  M%  ""
.      6v!   X   44\ +K'>!$r]pW`/RE/!IYe=,IkQ"N00A-Z4L#wg!:`c 7  U5    0   r2            P       +K'
.   d$  A!        &   @   pp    /\8~j@&4i~DvoZgy_+BVW   4   ME  XXA ;KL U5k+rK      #   //  & (("
.     G'# " XxU5    MY* @@"!` Kk@ 0   <<X#6v#+00H(n*E%    '6@@Aa;KU5    ,$,KDcc 7v    ,$,KDcc ,K!   8
.(8vDca ! !   ,$,KDcc ,K"   8(8vDc` 7v!   ,$,KyxWv+K!   ,$,KDcc ,K#   P(6vDcD!!     8$+KDcD!,K    h(
.  )(  U5, r24$E%    +K+2@ P   >~VvU5!   &"+K{x7v      znc"C#  ``>*0 8   HH  cK$ 0     <<6v      4 A!
.    ``# d$2 `     &f  "     p E%    6v' I)h b"    U5' (     C#U5      - P@C#U5        Kk&&U5      UK
.A!A!  E%E%    ppW$  UP  "     p E%      $ I)I!b"    U5! (     @ @ z:    ? P@h(U5      e @@Ra  eEd<5
. 2*E%A!  +K{*@ P   >~tx+K      h"    6v# d$T"` 0   003!8v    Euq*j*    Q U5"A+K      $ "         55
.        ;[c!" "   A!  g"7v      8,b"`   U5U5  )I4>"d\bWJ9i!d>   ``- 88Y)j*E%    2'@     hh_ !     P8
.E%A!  ``, r2r"E%    +Kx*@ (   XX` ,K    <$6vpM  !     )!b"    U5F%( (       |*# $ "   fFb500(   "
.   W7;K@@@   $       q5& ( $   |<0K      M!A!`   U5# d$C!`     &f  " !   p E%b"  ``, r2z*j*      = @
.     A!A!      )!+KcA6v+K    z"b"A!  U5U5                    R"  WP  " !   u%E%b"  +K1 0 (   RR  SK$
. 0 (   f&+K+K      +Ke"7v      5!A!    uU  $ "       c{  !     )!b",L        5!A!      b"b"1 @     #
.C  a`@       A!A!    ttB"+KFc# 7v    QYE%    +KZ)@ (   *j  gw\ 0 $   Y9Kv      xlb"A!  ``l$( "   i)
.  q5$ (     @ @       = @ (   Q1+K!!- @     hh  'w26@     >~RvU5    :"+KEcD!,K    Eum*E%    ? E%i!6v
.+K  ww8 0     $$+K      $ "         6v        pp  Gw( 0     <<6v      T A!    pp! #": `     3S! B"1
. @     .n` ,K    S#G%A!  ``, r2r"E%    +K& 0     f&;K6v      U5NL7v      znc",L  U5    CKG%""! U5
.      +K{x7v      h<b"    ``x$(     Q1  q5" ( "   S3+K      t A!    00# d$2 ` 0   z:  8v    ( (
.     6v& M-0(b"    ``x$(     ` @                   ``# r2U%E%    +K@'0     ddKv      W!U5ML6v      t
. A!        B"A @     XX  !     H b"`       E%B `     &f  -Ka       z:! "       $ |x6v      T A!&6
.        ! !     _   Gw( 0     Q16v      jvA!A!    b"b"1 @     #C  a`@       A!A!    tt    x66v
.      T A!&6        J `     }]! ##1 @     M-  !     )!b"    U5% (     22  i5> ( "   W7IK+K    h +K+K
.  wwP 0     $$+K      $ "           !   8   pp  Gw@ 0     'G6v      t A!    pp! #"Z `     uU! C#9 @
. 0   3S,!,K    0 ( ~>N2-35^^1.         . KkAa+K+K    CKG%A!  +Kc"0 (   **  cK@ 0     ddKv+K    7?F%b
."  ``2 M-z*j*      = @         cK@ 0     'G6v      " "     34# d$2 ` @   &f  " !   p E%b"  +Ka5uUe%j
.*j*    Z ` #+        % @ 0   A!A!    tt*"+Kf"7v      5!A!    uU  $ "   D$n*U5    6v6vu5U5      Z ` #
.+      6v6v    6v?   kK@ 0     'G6v@@0       Q16v+K    >"+KqM  !     i!b"    U5# ( $   S3+K      -!U
.5ml7vU5    [cH%b"  +K$ b"A!+K{x6v      4 A!    E%E%  "   Z"WwYX  !     v"+K^y! KkIYJ Y)j*j*    qKA!"
."  @@95( "     &6      0 U576+K      4(A!`   j*j*    uU/   \"  JJ        z*' $ "   {;Z500(       W7-
.K+K    *"6vnl6v+K    QYz*    6v    P8E%b"  +K0'0     j*  {K0 0     /OZv+K    ( $ Q1fSDkk-| ThoL#(
.    6vKk66+K      t A!    E%E%    A!f$  f"7v      t A!    uUU50     `   j*# f&b `     z:j*(     @
.   z:! "     ( (     A%' I)l$b"""  ``W#(     W7-K+K    *"  ol6v+K    P8E%b"  +Kg*@     b"A!    Uu  `
.`?   A%    < ``ml6v+K    P8E%$$  +KR!0 (       "6. ( &   W7-K@@0   (   A!`     jJ  Kk/   `"    X KkF
.F+K``    P8E%b"  +KR!0 ,   aA  $L< 0 0   $$Ww      !   k+^5U5    h<M%    j*    %!``nl6vU5!   T<{*
.    +K    !Qn*j*    !Kf"    E%    9 PP33U5+K    8,b"b"  ``h ( $   W7-KU5!   *"+KGc! 7v    P8E%$$  +K
.R!0 0   /O:v+K    B"+KFc! 7v    P8E%b"  +KR5@ 0   &f  Gw0 0     <<6v+K    )!b"A!  +K& I)j"b"    U5%
. (     C#U5U5    Z ``Xw+K      " "     uU" $     2"b")f! "     d$6vFcB!!     P8E%b"  +K=,@ 0   hh  '
.wu5@     XX  !     :"+Kd"wvU5    i!b"    ``& f&F"B!@   @@D $ "   J*  l*! ` @ Kk&&U5      * `     b"b
."6v!       NL7v      a5c",L  ``!   _gH%I)      U54$E%b"  +K+2@ P   >~Vv@@0   <   **  cK$ 0 (   /O6v+
.K    7?F%    ``# r2U%E%    +K@'0     ddKv      )!``ML6v      t A!    E%E%6v)kS[j$0 x*$ $     a!j*j*
.    J `         Ww\ 0 (   /Orv@@0   (   /Orv``    *"+KGc# 7v    T<F%    +KZ)@ 0   >~rv+K    >"+KGc#
. ,K    P E%    +KZ)@ 0   >~rv+K    t +Khh  'w( 0     ` `     jJJ U5..  ( ' I)2*E%    +KX#0     OoUvU
.5    5!+Ke"7vU5    $ $     U5' (     D$E%{U# $ !   I)  x*L%$     Tt\5      ,&` 0   ;[! a!lK`     &f!
. "     T$6vEcD!,K    !Qm*      ? E%5} 6jV$ 6v]   P       ``"   7#  C#  uU    ,   A!
.                          $                     M-  +K"   (
.                                                                         )GPUI95";
extern const int kShaderPSQuadSize = 4864;
uint8_t kShaderPSQuadBytes[4864] = {};

extern const char kShaderVSTri95[] = R"GPUI95(
.Ea8fCSyEPsc6SEvQy20tOd!64     6 +K"   D$  @@*   $"  VF  PP3 6v"NkAS/! E%    R   (   pp    C#4v\5##mM
.1   %|^|&%  @@    (   a!  88  6v!       ~>                          $   `   KkLDk|4OsFKk"   #   J*
.  +K!           ;[%       @   A!    8       &v5vi*    4v5v@!  6vT   0   b"        ""      tt5v5v
.    &v5vi*    z(  j*    "       ?_!       5v5v_   Kk5v5v'   +K'   (   0       +K^       uu5vT5    2v
.5va"    G!  Q!  b"        9%      Ss5v5v!   uu5vT5    77  uU    "       6v!       5v5v_   Kk5v5v'
.   GgG./BCLOTJn@@C]$MK:<voZ 26v! " 0                             s'  GGiy5$c3<R1P&8%Di>8 GAy>Fn)!{C
.  # $ `                             B2  GgJYTH=)NTInk'd)= GAy>Fn  ``  ! $
.                             3%  n^\[$/RF8d"?LSLB(1V "8&1bf/.mA#CSi%mP2i2YfXwzX?K.N%<#weyF0DRm$HV4]P
./QDVQ;8L@X|a`G=+T-Y63E$  ""  6v    p           +K!       $$& U56           @@    "   ;{' pp%
.           ((  6v    (l! U5`Cb8-9kQ3 ,I)gJWU5`+fzPrq-B o1!,l%! 6v    0   #C        !   P       +K'
.   i)            ,   `   Kk!   V"          6v!   0   44  6v>   $       @@    &   !!& 00^Y%6"EQCM9OT;
. ,I)gJWU5`+fzPrq-B i3<Wb@n-  U5k*  I   x(" Dc" A!63C!    b"  +KO 00H(n*    6vO 00hH]5j*     "``llWv+
.K    @$  mlwv      "   "B  a5)+0 $   $d  CK26@ 0   qQ! fva5@ 8   uU! KK    T$  |xwv      $ "
.                 +KEF  b"9 @     >~Vv      M!f"          9 PP##r*      % @     A!A!    6v" "     m.#
. f&Xv`     &f  -Ka       b"b"      % $     Ac& f&)%B!@   @@)%$ !   ))  t*T%$ "   k+d5U5    -!U5bAvv`
.`    z"c"    ``' A!=7 +E;"   "   $       Kk    &           6v
.                                                      A!
.                                                                                 )GPUI95";
extern const int kShaderVSTriSize = 1408;
uint8_t kShaderVSTriBytes[1408] = {};

extern const char kShaderPSTri95[] = R"GPUI95(
.Ea8fRB~7,bB9AFpm.7`Ou.Hm4   @@: 6v"   D$  +K"   k   o/  ``* 6v"NkAt0                pp    C#5v\5##Kk
.!   %|^|&%  @@    (   a!  88  6v!       y92)=jhm`BY3&V6.o*)A7}s*I6I~.BIw:nqDI9a>&m<|0O,APP-Y63V%  b"
.  6v    )!      b"  +K!       44    =           @@    "   ;{' uU'           ((  6v    (l! .n! +K
.        $$  ``    L@  Y9(o&;CTs($gkm1KU4_nd;uUo%a68I/}>v*5{nB:d   @   U5    <           ``        **
.    '   "       00    !   R"  3SygoXn,S\XfA@nYI6o%;0!   %   l   q1$ l*h"""_MA!@   j*h"""_MA!`   j*h"
.""]KA!!!  z:& ""jx`     M-# !!EL` 0   U5# vv    ,$6vFc  !     z"c"""  ``M%( $   P0  q58 (     wWIK+K
.    CKG%$$  6v' I)h b"    U5% (     C#U5      \ Kk&&U5      : `     z:  "     %%6v;8  !     J"b"
.    U5! (     D$E%{U  $     I)  x*L%$     Ttd5j*    8,c"`   ``& f&f"B!    uUe"$ !   ))  t*T%$ !   Tt
.d5j*    =!U5wW/'?}2   4   @       6v"   8       ``    $
.                                                     E%
.                                                                                  )GPUI95";
extern const int kShaderPSTriSize = 844;
uint8_t kShaderPSTriBytes[844] = {};

} // namespace gpuw
} // namespace gpui
#endif
